config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'board/index'
  get 'board/backend'

  get 'admins/dashboard', to: 'admins#dashboard', as: 'admin_root'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def dashboard
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
  end

  def backend
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/admins/dashboard.html.slim
p This is admin dashboard

- if admin_signed_in?
  li
    = link_to('Logout', destroy_admin_session_path, :method => :delete)

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/board/backend.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="#"金保证财富后台管理系统
    .navbar-collapse.collapse.navbar-responsive-collapse
      ul.nav.navbar-nav
        li= link_to "Link 1", "/path1"
        li= link_to "Link 2", "/path2"
        li= link_to "Link 3", "/path3"
    - if admin_signed_in?
      li
        = link_to('Logout', destroy_admin_session_path, :method => :delete)       
    / - else
    /   li
    /     = link_to('Login', new_admin_session_path)

.container
  .row
    .col-lg-9
      = bootstrap_flash
      .row
        .col-lg-6 
          .well 
            '您是
            = link_to "系统管理员", new_admin_session_path
        .col-lg-6 
          .well 您是理财专员
    .col-lg-3
      .well.sidebar-nav
        p 快速导航
        ul.nav.nav-list
          li.nav-header Sidebar
          li= link_to "Link 1", "/path1"
          li= link_to "Link 2", "/path2"
          li= link_to "Link 3", "/path3"
        ul.nav.nav-list
          li.nav-header Sidebar
          li= link_to "Link 1", "/path1"
          li= link_to "Link 2", "/path2"
          li= link_to "Link 3", "/path3"

  footer
    p &copy; 金保证财富管理 2013 - 2015

app/views/board/index.html.slim
h1 Board#index
p Find me in app/views/board/index.html.slim

a.btn.btn-primary href='#' this is a link button

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "金保证财富管理"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
  
  body
    .container
      = yield